import { step, tour } from './types';

/** The steps every admin screen ends with: the "?" button and the menu. */
const helpStep = step(
  'help-button',
  ['The “?” button', '“?” ಗುಂಡಿ'],
  ['It is on every screen, at the top.', 'ಇದು ಪ್ರತಿ ಪುಟದ ಮೇಲ್ಭಾಗದಲ್ಲಿದೆ.'],
  ['It plays the tour for the screen you are on, any time you want.', 'ನೀವು ಇರುವ ಪುಟದ ಪರಿಚಯವನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ತೋರಿಸುತ್ತದೆ.'],
  ['This tour starts again. Nothing changes in the shop.', 'ಈ ಪರಿಚಯ ಮತ್ತೆ ಶುರುವಾಗುತ್ತದೆ. ಅಂಗಡಿಯಲ್ಲಿ ಏನೂ ಬದಲಾಗುವುದಿಲ್ಲ.'],
);

export const homeTour = tour('home', ['Home', 'ಮುಖಪುಟ'], [
  step(
    undefined,
    ['Welcome', 'ಸ್ವಾಗತ'],
    ['This is the stock website for the shop and its godowns.', 'ಇದು ಅಂಗಡಿ ಮತ್ತು ಗೋದಾಮುಗಳ ಸ್ಟಾಕ್ ವೆಬ್‌ಸೈಟ್.'],
    ['Every bill from billing takes stock down here by itself. You fix what it cannot match, and bring goods in when they run low.', 'ಬಿಲ್ಲಿಂಗ್‌ನ ಪ್ರತಿ ಬಿಲ್ ಇಲ್ಲಿ ಸ್ಟಾಕ್ ತಾನಾಗಿ ಕಡಿಮೆ ಮಾಡುತ್ತದೆ. ಹೊಂದದ್ದನ್ನು ನೀವು ಸರಿಪಡಿಸಿ, ಕಡಿಮೆಯಾದಾಗ ಸಾಮಾನು ತರಿಸಿ.'],
    ['Tap Next to see each part. Skip ends the tour; the “?” button brings it back.', 'ಪ್ರತಿ ಭಾಗ ನೋಡಲು ಮುಂದೆ ಒತ್ತಿ. ಬಿಡಿ ಒತ್ತಿದರೆ ಮುಗಿಯುತ್ತದೆ; “?” ಗುಂಡಿ ಮತ್ತೆ ತೋರಿಸುತ್ತದೆ.'],
  ),
  step(
    'nav-home',
    ['The menu: five places', 'ಮೆನು: ಐದು ಭಾಗಗಳು'],
    ['Home, Bills, Inventory, Buy & move and Setup.', 'ಮುಖಪುಟ, ಬಿಲ್‌ಗಳು, ಸಾಮಾನು, ಖರೀದಿ ಮತ್ತು ಸಾಗಣೆ, ಸೆಟಪ್.'],
    ['Each place is one screen with a few tabs inside.', 'ಪ್ರತಿ ಭಾಗ ಒಂದು ಪುಟ, ಒಳಗೆ ಕೆಲವು ಟ್ಯಾಬ್‌ಗಳು.'],
    ['That place opens. On a phone, “More” holds Buy & move and Setup.', 'ಆ ಭಾಗ ತೆರೆಯುತ್ತದೆ. ಫೋನಿನಲ್ಲಿ “ಇನ್ನಷ್ಟು” ಒಳಗೆ ಖರೀದಿ ಮತ್ತು ಸೆಟಪ್ ಇವೆ.'],
  ),
  step(
    'home-link',
    ['Billing link', 'ಬಿಲ್ಲಿಂಗ್ ಸಂಪರ್ಕ'],
    ['Whether stock is reading bills from the billing app.', 'ಸ್ಟಾಕ್ ಬಿಲ್ಲಿಂಗ್ ಆ್ಯಪ್‌ನಿಂದ ಬಿಲ್ ಓದುತ್ತಿದೆಯೇ ಎಂದು.'],
    ['Green means new bills arrive within seconds and take stock down.', 'ಹಸಿರು ಎಂದರೆ ಹೊಸ ಬಿಲ್‌ಗಳು ಕೆಲವೇ ಸೆಕೆಂಡಿನಲ್ಲಿ ಬಂದು ಸ್ಟಾಕ್ ಕಡಿಮೆ ಮಾಡುತ್ತವೆ.'],
    ['Nothing: it only shows. Setup → Settings has “Read bills now”.', 'ಏನೂ ಇಲ್ಲ: ಇದು ತೋರಿಸುತ್ತದೆ ಮಾತ್ರ. ಸೆಟಪ್ → ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ “ಈಗಲೇ ಬಿಲ್ ಓದಿ” ಇದೆ.'],
  ),
  step(
    'home-needs',
    ['Needs you now', 'ಈಗ ನಿಮ್ಮ ಗಮನ ಬೇಕು'],
    ['Four cards: lines to digitise, running low, below zero, transfers on the way.', 'ನಾಲ್ಕು ಕಾರ್ಡ್: ಡಿಜಿಟೈಸ್ ಮಾಡಬೇಕಾದ ಸಾಲು, ಮುಗಿಯುತ್ತಿರುವುದು, ಸೊನ್ನೆಗಿಂತ ಕಡಿಮೆ, ದಾರಿಯಲ್ಲಿರುವ ಸಾಗಣೆ.'],
    ['The number says how many are waiting. Coloured means do it today.', 'ಸಂಖ್ಯೆ ಎಷ್ಟು ಬಾಕಿ ಎಂದು ಹೇಳುತ್ತದೆ. ಬಣ್ಣ ಇದ್ದರೆ ಇಂದೇ ಮಾಡಿ.'],
    ['You go straight to that list, ready to act.', 'ನೇರವಾಗಿ ಆ ಪಟ್ಟಿಗೆ ಹೋಗುತ್ತೀರಿ.'],
  ),
  step(
    'home-just-low',
    ['Just went low', 'ಈಗಷ್ಟೇ ಕಡಿಮೆಯಾಗಿದೆ'],
    ['Items a sale took below their level today.', 'ಇಂದು ಮಾರಾಟದಿಂದ ಮಿತಿಗಿಂತ ಕಡಿಮೆಯಾದ ಸಾಮಾನು.'],
    ['It tells you what to bring from the godown or buy next.', 'ಗೋದಾಮಿನಿಂದ ಏನು ತರಿಸಬೇಕು ಅಥವಾ ಏನು ಕೊಳ್ಳಬೇಕು ಎಂದು ಹೇಳುತ್ತದೆ.'],
    ['That item’s page opens, with its stock in every place.', 'ಆ ಸಾಮಾನಿನ ಪುಟ ತೆರೆಯುತ್ತದೆ, ಎಲ್ಲಾ ಕಡೆಯ ಸ್ಟಾಕ್ ಜೊತೆ.'],
  ),
  step(
    'home-week',
    ['The last 7 days', 'ಕಳೆದ 7 ದಿನ'],
    ['Sales for each day, today in the darker colour.', 'ಪ್ರತಿ ದಿನದ ಮಾರಾಟ, ಇಂದು ಗಾಢ ಬಣ್ಣದಲ್ಲಿ.'],
    ['A quick look at how the week is going.', 'ವಾರ ಹೇಗೆ ಸಾಗುತ್ತಿದೆ ಎಂದು ಒಮ್ಮೆ ನೋಡಲು.'],
    ['Pointing at a day shows its total and number of bills.', 'ಒಂದು ದಿನದ ಮೇಲೆ ಇಟ್ಟರೆ ಅದರ ಮೊತ್ತ ಮತ್ತು ಬಿಲ್ ಸಂಖ್ಯೆ ಕಾಣುತ್ತದೆ.'],
  ),
  step(
    'home-moving',
    ['Moving now', 'ಈಗ ನಡೆಯುತ್ತಿರುವುದು'],
    ['Goods asked from godowns, on the way, and open purchase orders.', 'ಗೋದಾಮಿನಿಂದ ಕೇಳಿದ್ದು, ದಾರಿಯಲ್ಲಿರುವುದು, ತೆರೆದ ಖರೀದಿ ಆರ್ಡರ್.'],
    ['Stock changes only when these are received.', 'ಇವು ಬಂದಾಗ ಮಾತ್ರ ಸ್ಟಾಕ್ ಬದಲಾಗುತ್ತದೆ.'],
    ['Buy & move opens on that list.', 'ಖರೀದಿ ಮತ್ತು ಸಾಗಣೆ ಆ ಪಟ್ಟಿಯಲ್ಲಿ ತೆರೆಯುತ್ತದೆ.'],
  ),
  step(
    'home-today',
    ['Today', 'ಇಂದು'],
    ['Today’s sales, money still due, and stock value at cost.', 'ಇಂದಿನ ಮಾರಾಟ, ಬರಬೇಕಾದ ಹಣ, ಖರೀದಿ ಬೆಲೆಯಲ್ಲಿ ಸ್ಟಾಕ್ ಮೌಲ್ಯ.'],
    ['Numbers only; they update by themselves as bills come in.', 'ಸಂಖ್ಯೆಗಳು ಮಾತ್ರ; ಬಿಲ್ ಬಂದಂತೆ ತಾನಾಗಿ ಬದಲಾಗುತ್ತವೆ.'],
    ['Nothing. For more, the Reports tab is at the top of Home.', 'ಏನೂ ಇಲ್ಲ. ಹೆಚ್ಚಿಗೆ, ಮುಖಪುಟದ ಮೇಲೆ ವರದಿ ಟ್ಯಾಬ್ ಇದೆ.'],
  ),
  helpStep,
]);

export const reportsTour = tour('reports', ['Reports', 'ವರದಿಗಳು'], [
  step(
    'section-tabs',
    ['Home · Reports', 'ಮುಖಪುಟ · ವರದಿ'],
    ['Reports sit next to Home.', 'ವರದಿಗಳು ಮುಖಪುಟದ ಪಕ್ಕದಲ್ಲಿವೆ.'],
    ['They are read-only: nothing here changes stock.', 'ಇವು ಓದಲು ಮಾತ್ರ: ಇಲ್ಲಿ ಸ್ಟಾಕ್ ಬದಲಾಗುವುದಿಲ್ಲ.'],
    ['Home goes back to the day’s summary.', 'ಮುಖಪುಟ ಇಂದಿನ ಸಾರಾಂಶಕ್ಕೆ ಹಿಂತಿರುಗುತ್ತದೆ.'],
  ),
  step(
    'reports-dates',
    ['Dates', 'ದಿನಾಂಕ'],
    ['From and to: the days the report covers.', 'ಇಂದ ಮತ್ತು ವರೆಗೆ: ವರದಿಯ ದಿನಗಳು.'],
    ['Every tab below uses these days.', 'ಕೆಳಗಿನ ಎಲ್ಲಾ ಟ್ಯಾಬ್‌ಗಳು ಈ ದಿನಗಳನ್ನು ಬಳಸುತ್ತವೆ.'],
    ['A calendar opens; the report changes when you pick a day.', 'ಕ್ಯಾಲೆಂಡರ್ ತೆರೆಯುತ್ತದೆ; ದಿನ ಆರಿಸಿದಾಗ ವರದಿ ಬದಲಾಗುತ್ತದೆ.'],
  ),
  step(
    'reports-quick',
    ['Quick dates', 'ಬೇಗ ದಿನಾಂಕ'],
    ['Today, 7 days, 30 days.', 'ಇಂದು, 7 ದಿನ, 30 ದಿನ.'],
    ['Sets both dates in one tap.', 'ಒಂದೇ ಒತ್ತಿನಲ್ಲಿ ಎರಡೂ ದಿನಾಂಕ ಹೊಂದಿಸುತ್ತದೆ.'],
    ['The report reloads for that span.', 'ಆ ಅವಧಿಗೆ ವರದಿ ಮತ್ತೆ ಬರುತ್ತದೆ.'],
  ),
  step(
    'reports-tabs',
    ['Kinds of report', 'ವರದಿಯ ಬಗೆಗಳು'],
    ['Sales by item, stock value, fast and slow, prices outside range, trips by vehicle.', 'ಸಾಮಾನು ಪ್ರಕಾರ ಮಾರಾಟ, ಸ್ಟಾಕ್ ಮೌಲ್ಯ, ವೇಗ ಮತ್ತು ನಿಧಾನ, ಮಿತಿ ಮೀರಿದ ಬೆಲೆ, ವಾಹನದ ಓಡಾಟ.'],
    ['Each answers one question about the shop.', 'ಪ್ರತಿಯೊಂದು ಅಂಗಡಿಯ ಬಗ್ಗೆ ಒಂದು ಪ್ರಶ್ನೆಗೆ ಉತ್ತರ.'],
    ['That report shows below.', 'ಆ ವರದಿ ಕೆಳಗೆ ಕಾಣುತ್ತದೆ.'],
  ),
  step(
    'reports-sales',
    ['Takings', 'ಆದಾಯ'],
    ['The total, split into lines linked to an item and lines not linked yet.', 'ಒಟ್ಟು, ಸಾಮಾನಿಗೆ ಜೋಡಿಸಿದ ಸಾಲು ಮತ್ತು ಇನ್ನೂ ಜೋಡಿಸದ ಸಾಲುಗಳಾಗಿ.'],
    ['“Not linked” shrinks as you digitise lines in Bills → To digitise.', 'ಬಿಲ್ → ಡಿಜಿಟೈಸ್ ಮಾಡಿ ಯಲ್ಲಿ ಸಾಲು ಡಿಜಿಟೈಸ್ ಮಾಡಿದಂತೆ “ಜೋಡಿಸಿಲ್ಲ” ಕಡಿಮೆಯಾಗುತ್ತದೆ.'],
    ['Nothing: these are totals.', 'ಏನೂ ಇಲ್ಲ: ಇವು ಮೊತ್ತಗಳು.'],
  ),
  step(
    'reports-excel',
    ['Excel', 'ಎಕ್ಸೆಲ್'],
    ['A download of the table you see.', 'ನೀವು ನೋಡುತ್ತಿರುವ ಪಟ್ಟಿಯ ಡೌನ್‌ಲೋಡ್.'],
    ['Opens in Excel with Kannada names intact.', 'ಕನ್ನಡ ಹೆಸರುಗಳ ಜೊತೆ ಎಕ್ಸೆಲ್‌ನಲ್ಲಿ ತೆರೆಯುತ್ತದೆ.'],
    ['The file is saved to this computer or phone.', 'ಫೈಲ್ ಈ ಕಂಪ್ಯೂಟರ್ ಅಥವಾ ಫೋನಿನಲ್ಲಿ ಉಳಿಯುತ್ತದೆ.'],
  ),
  helpStep,
]);

export const billsTour = tour('bills', ['Bills', 'ಬಿಲ್‌ಗಳು'], [
  step(
    'section-tabs',
    ['Bills · To digitise', 'ಬಿಲ್‌ಗಳು · ಡಿಜಿಟೈಸ್ ಮಾಡಿ'],
    ['Two tabs: every bill, and the lines waiting for you.', 'ಎರಡು ಟ್ಯಾಬ್: ಎಲ್ಲಾ ಬಿಲ್‌ಗಳು, ಮತ್ತು ನಿಮಗಾಗಿ ಕಾಯುತ್ತಿರುವ ಸಾಲುಗಳು.'],
    ['Bills shows what happened; To digitise is where you act.', 'ಬಿಲ್‌ಗಳು ಏನಾಯಿತು ಎಂದು ತೋರಿಸುತ್ತದೆ; ಡಿಜಿಟೈಸ್ ಮಾಡಿ ಯಲ್ಲಿ ನೀವು ಕೆಲಸ ಮಾಡುತ್ತೀರಿ.'],
    ['That tab opens.', 'ಆ ಟ್ಯಾಬ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  step(
    'bills-intro',
    ['Bills from billing', 'ಬಿಲ್ಲಿಂಗ್‌ನಿಂದ ಬಂದ ಬಿಲ್‌ಗಳು'],
    ['Every bill made at the counter, newest first.', 'ಕೌಂಟರ್‌ನಲ್ಲಿ ಮಾಡಿದ ಪ್ರತಿ ಬಿಲ್, ಹೊಸದು ಮೊದಲು.'],
    ['Stock reads them from billing by itself; you never type them twice.', 'ಸ್ಟಾಕ್ ಇವನ್ನು ಬಿಲ್ಲಿಂಗ್‌ನಿಂದ ತಾನಾಗಿ ಓದುತ್ತದೆ; ಎರಡು ಸಲ ಟೈಪ್ ಮಾಡಬೇಕಿಲ್ಲ.'],
    ['Nothing: it is a list to read.', 'ಏನೂ ಇಲ್ಲ: ಓದುವ ಪಟ್ಟಿ.'],
  ),
  step(
    'bills-card',
    ['One bill', 'ಒಂದು ಬಿಲ್'],
    ['Bill number, customer, time and each line.', 'ಬಿಲ್ ಸಂಖ್ಯೆ, ಗ್ರಾಹಕ, ಸಮಯ ಮತ್ತು ಪ್ರತಿ ಸಾಲು.'],
    ['Under a line, the item it took stock from, and how much.', 'ಸಾಲಿನ ಕೆಳಗೆ, ಯಾವ ಸಾಮಾನಿನ ಸ್ಟಾಕ್ ಎಷ್ಟು ಕಡಿಮೆಯಾಯಿತು.'],
    ['Nothing: bills are changed in the billing app only.', 'ಏನೂ ಇಲ್ಲ: ಬಿಲ್‌ಗಳನ್ನು ಬಿಲ್ಲಿಂಗ್ ಆ್ಯಪ್‌ನಲ್ಲಿ ಮಾತ್ರ ಬದಲಿಸಬಹುದು.'],
  ),
  step(
    'bills-total',
    ['Total, rounded', 'ಒಟ್ಟು, ರೌಂಡ್'],
    ['The amount as the counter collects it, with the round-off beside it.', 'ಕೌಂಟರ್ ತೆಗೆದುಕೊಳ್ಳುವ ಮೊತ್ತ, ಪಕ್ಕದಲ್ಲಿ ರೌಂಡ್ ಆಫ್.'],
    ['“Due” in yellow means the customer still owes money on this bill.', 'ಹಳದಿ “ಬಾಕಿ” ಎಂದರೆ ಈ ಬಿಲ್‌ನಲ್ಲಿ ಗ್ರಾಹಕ ಇನ್ನೂ ಹಣ ಕೊಡಬೇಕು.'],
    ['Nothing. The rounding is set in Setup → Settings.', 'ಏನೂ ಇಲ್ಲ. ರೌಂಡಿಂಗ್ ಸೆಟಪ್ → ಸೆಟ್ಟಿಂಗ್ಸ್‌ನಲ್ಲಿ.'],
  ),
  step(
    'bills-state',
    ['How each line moved stock', 'ಪ್ರತಿ ಸಾಲು ಸ್ಟಾಕ್ ಬದಲಿಸಿದ ಬಗೆ'],
    ['Matched, digitised, to digitise, or not stock.', 'ಹೊಂದಿದೆ, ಡಿಜಿಟೈಸ್ ಆಗಿದೆ, ಡಿಜಿಟೈಸ್ ಮಾಡಬೇಕು, ಅಥವಾ ಸ್ಟಾಕ್ ಅಲ್ಲ.'],
    ['“To digitise” lines have not moved stock yet: they wait for you.', '“ಡಿಜಿಟೈಸ್ ಮಾಡಬೇಕು” ಸಾಲುಗಳು ಇನ್ನೂ ಸ್ಟಾಕ್ ಬದಲಿಸಿಲ್ಲ: ನಿಮಗಾಗಿ ಕಾಯುತ್ತಿವೆ.'],
    ['Nothing here; open the To digitise tab to answer them.', 'ಇಲ್ಲಿ ಏನೂ ಇಲ್ಲ; ಉತ್ತರಿಸಲು ಡಿಜಿಟೈಸ್ ಮಾಡಿ ಟ್ಯಾಬ್ ತೆರೆಯಿರಿ.'],
  ),
  step(
    'nav-bills',
    ['Back here any time', 'ಯಾವಾಗ ಬೇಕಾದರೂ ಇಲ್ಲಿಗೆ'],
    ['Bills in the menu.', 'ಮೆನುವಿನಲ್ಲಿ ಬಿಲ್‌ಗಳು.'],
    ['Opens the bills list, with To digitise as its second tab.', 'ಬಿಲ್ ಪಟ್ಟಿ ತೆರೆಯುತ್ತದೆ, ಎರಡನೇ ಟ್ಯಾಬ್ ಡಿಜಿಟೈಸ್ ಮಾಡಿ.'],
    ['The Bills tab opens.', 'ಬಿಲ್‌ಗಳ ಟ್ಯಾಬ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  helpStep,
]);

export const confirmTour = tour('confirm', ['To digitise', 'ಡಿಜಿಟೈಸ್ ಮಾಡಿ'], [
  step(
    undefined,
    ['Lines waiting for you', 'ನಿಮಗಾಗಿ ಕಾಯುತ್ತಿರುವ ಸಾಲುಗಳು'],
    ['Handwritten bill lines, and typed names that match no item.', 'ಕೈಬರಹದ ಬಿಲ್ ಸಾಲುಗಳು, ಮತ್ತು ಯಾವ ಸಾಮಾನಿಗೂ ಹೊಂದದ ಹೆಸರುಗಳು.'],
    ['Stock cannot guess these. Until you pick the item, they do not move stock.', 'ಸ್ಟಾಕ್ ಇವನ್ನು ಊಹಿಸಲಾಗದು. ನೀವು ಸಾಮಾನು ಆರಿಸುವವರೆಗೆ ಸ್ಟಾಕ್ ಬದಲಾಗುವುದಿಲ್ಲ.'],
    ['Tap Next to see how to clear them.', 'ಹೇಗೆ ಮುಗಿಸುವುದು ಎಂದು ನೋಡಲು ಮುಂದೆ ಒತ್ತಿ.'],
  ),
  step(
    'confirm-find',
    ['Find a bill', 'ಬಿಲ್ ಹುಡುಕಿ'],
    ['Type a customer’s name or a bill number, like #75.', 'ಗ್ರಾಹಕರ ಹೆಸರು ಅಥವಾ ಬಿಲ್ ಸಂಖ್ಯೆ, ಉದಾ #75, ಟೈಪ್ ಮಾಡಿ.'],
    ['Only the bills that match stay on the screen.', 'ಹೊಂದುವ ಬಿಲ್‌ಗಳು ಮಾತ್ರ ಪರದೆಯಲ್ಲಿ ಉಳಿಯುತ್ತವೆ.'],
    ['The keyboard opens; clear the box to see all again.', 'ಕೀಬೋರ್ಡ್ ತೆರೆಯುತ್ತದೆ; ಎಲ್ಲವೂ ಕಾಣಲು ಡಬ್ಬಿ ಖಾಲಿ ಮಾಡಿ.'],
  ),
  step(
    'confirm-sort',
    ['Oldest or newest first', 'ಹಳೆಯದು ಅಥವಾ ಹೊಸದು ಮೊದಲು'],
    ['The order of the bills.', 'ಬಿಲ್‌ಗಳ ಕ್ರಮ.'],
    ['Oldest first clears the backlog; newest first follows the counter.', 'ಹಳೆಯದು ಮೊದಲು ಬಾಕಿ ಮುಗಿಸುತ್ತದೆ; ಹೊಸದು ಮೊದಲು ಕೌಂಟರ್ ಜೊತೆ ಸಾಗುತ್ತದೆ.'],
    ['The list re-orders. Nothing else changes.', 'ಪಟ್ಟಿಯ ಕ್ರಮ ಬದಲಾಗುತ್ತದೆ. ಬೇರೇನೂ ಇಲ್ಲ.'],
  ),
  step(
    'confirm-bill',
    ['One card per bill', 'ಪ್ರತಿ ಬಿಲ್‌ಗೆ ಒಂದು ಕಾರ್ಡ್'],
    ['A bill and the lines on it that need you.', 'ಒಂದು ಬಿಲ್ ಮತ್ತು ನಿಮ್ಮ ಗಮನ ಬೇಕಾದ ಅದರ ಸಾಲುಗಳು.'],
    ['You answer a whole bill at once, the way it was written.', 'ಬರೆದಂತೆಯೇ ಇಡೀ ಬಿಲ್‌ಗೆ ಒಮ್ಮೆಲೇ ಉತ್ತರಿಸುತ್ತೀರಿ.'],
    ['Tapping the bill’s name opens or closes its lines.', 'ಬಿಲ್ ಹೆಸರು ಒತ್ತಿದರೆ ಸಾಲುಗಳು ತೆರೆಯುತ್ತವೆ ಅಥವಾ ಮುಚ್ಚುತ್ತವೆ.'],
  ),
  step(
    'confirm-written',
    ['What was written', 'ಏನು ಬರೆದಿದ್ದರು'],
    ['The handwriting from the bill, with its quantity, rate and amount.', 'ಬಿಲ್‌ನ ಕೈಬರಹ, ಪ್ರಮಾಣ, ದರ ಮತ್ತು ಮೊತ್ತದ ಜೊತೆ.'],
    ['Read it, then pick the item it means.', 'ಓದಿ, ಅದು ಯಾವ ಸಾಮಾನು ಎಂದು ಆರಿಸಿ.'],
    ['Nothing: it is the writing itself.', 'ಏನೂ ಇಲ್ಲ: ಇದು ಬರಹ ಮಾತ್ರ.'],
  ),
  step(
    'confirm-search',
    ['Search the item', 'ಸಾಮಾನು ಹುಡುಕಿ'],
    ['Type a few letters, in English or Kannada.', 'ಕೆಲವು ಅಕ್ಷರ ಟೈಪ್ ಮಾಡಿ, ಇಂಗ್ಲಿಷ್ ಅಥವಾ ಕನ್ನಡದಲ್ಲಿ.'],
    ['Matching items appear as buttons; pick one, then the unit and quantity.', 'ಹೊಂದುವ ಸಾಮಾನುಗಳು ಗುಂಡಿಗಳಾಗಿ ಬರುತ್ತವೆ; ಒಂದನ್ನು ಆರಿಸಿ, ನಂತರ ಘಟಕ ಮತ್ತು ಪ್ರಮಾಣ.'],
    ['The item is chosen for this line. Stock does not move yet.', 'ಈ ಸಾಲಿಗೆ ಸಾಮಾನು ಆಯ್ಕೆಯಾಗುತ್ತದೆ. ಸ್ಟಾಕ್ ಇನ್ನೂ ಬದಲಾಗುವುದಿಲ್ಲ.'],
  ),
  step(
    'confirm-line-ok',
    ['Digitise', 'ಡಿಜಿಟೈಸ್ ಮಾಡಿ'],
    ['Digitises just this one line.', 'ಈ ಒಂದು ಸಾಲನ್ನು ಮಾತ್ರ ಡಿಜಿಟೈಸ್ ಮಾಡುತ್ತದೆ.'],
    ['Stock goes down in the shop, and the name is remembered for next time.', 'ಅಂಗಡಿಯ ಸ್ಟಾಕ್ ಕಡಿಮೆಯಾಗುತ್ತದೆ, ಹೆಸರು ಮುಂದಿನ ಸಲಕ್ಕೆ ನೆನಪಿರುತ್ತದೆ.'],
    ['The line leaves the list, and one line says what changed, like “Shop: Parle-G −2 pack”.', 'ಸಾಲು ಪಟ್ಟಿಯಿಂದ ಹೋಗುತ್ತದೆ, ಏನು ಬದಲಾಯಿತು ಎಂದು ಒಂದು ಸಾಲು ಹೇಳುತ್ತದೆ, ಉದಾ “ಅಂಗಡಿ: ಪಾರ್ಲೆ-ಜಿ −2 ಪ್ಯಾಕ್”.'],
  ),
  step(
    'confirm-not-stock',
    ['Not stock', 'ಸ್ಟಾಕ್ ಅಲ್ಲ'],
    ['For a service, a delivery charge or a note.', 'ಸೇವೆ, ಸಾಗಣೆ ಶುಲ್ಕ ಅಥವಾ ಟಿಪ್ಪಣಿಗೆ.'],
    ['Marks the line as money only, so it never touches stock.', 'ಸಾಲನ್ನು ಹಣ ಮಾತ್ರ ಎಂದು ಗುರುತಿಸುತ್ತದೆ, ಸ್ಟಾಕ್ ಮುಟ್ಟುವುದಿಲ್ಲ.'],
    ['The line leaves the list. Stock stays as it is.', 'ಸಾಲು ಪಟ್ಟಿಯಿಂದ ಹೋಗುತ್ತದೆ. ಸ್ಟಾಕ್ ಹಾಗೆಯೇ.'],
  ),
  step(
    'confirm-all',
    ['✓ Digitise all on this bill', '✓ ಈ ಬಿಲ್‌ನ ಎಲ್ಲಾ ಡಿಜಿಟೈಸ್ ಮಾಡಿ'],
    ['Digitises every line on the bill that has its item picked.', 'ಸಾಮಾನು ಆರಿಸಿದ ಬಿಲ್‌ನ ಎಲ್ಲಾ ಸಾಲುಗಳನ್ನು ಡಿಜಿಟೈಸ್ ಮಾಡುತ್ತದೆ.'],
    ['The fastest way: pick the items, then one tap for the whole bill.', 'ಅತಿ ಬೇಗದ ದಾರಿ: ಸಾಮಾನು ಆರಿಸಿ, ನಂತರ ಇಡೀ ಬಿಲ್‌ಗೆ ಒಂದು ಒತ್ತು.'],
    ['Those lines leave the list and stock goes down. Lines still missing an item stay for you.', 'ಆ ಸಾಲುಗಳು ಪಟ್ಟಿಯಿಂದ ಹೋಗುತ್ತವೆ, ಸ್ಟಾಕ್ ಕಡಿಮೆಯಾಗುತ್ತದೆ. ಸಾಮಾನು ಇಲ್ಲದ ಸಾಲುಗಳು ಉಳಿಯುತ್ತವೆ.'],
  ),
  helpStep,
]);

export const inventoryTour = tour('inventory', ['Inventory', 'ಸಾಮಾನು ಮತ್ತು ಸ್ಟಾಕ್'], [
  step(
    'section-tabs',
    ['Items & stock · Bring from godown', 'ಸಾಮಾನು ಮತ್ತು ಸ್ಟಾಕ್ · ಗೋದಾಮಿನಿಂದ ತರಿಸಿ'],
    ['Two tabs: every item with its stock, and the refill list.', 'ಎರಡು ಟ್ಯಾಬ್: ಸ್ಟಾಕ್ ಜೊತೆ ಎಲ್ಲಾ ಸಾಮಾನು, ಮತ್ತು ತರಿಸುವ ಪಟ್ಟಿ.'],
    ['The refill list plans one trip from the godown for everything low.', 'ತರಿಸುವ ಪಟ್ಟಿ ಕಡಿಮೆ ಇರುವುದೆಲ್ಲಕ್ಕೂ ಗೋದಾಮಿನಿಂದ ಒಂದೇ ಓಡಾಟ ಯೋಜಿಸುತ್ತದೆ.'],
    ['That tab opens.', 'ಆ ಟ್ಯಾಬ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  step(
    'inventory-search',
    ['Search', 'ಹುಡುಕಿ'],
    ['Find an item by any of its names, English or Kannada.', 'ಯಾವುದೇ ಹೆಸರಿನಿಂದ ಸಾಮಾನು ಹುಡುಕಿ, ಇಂಗ್ಲಿಷ್ ಅಥವಾ ಕನ್ನಡ.'],
    ['The list below narrows as you type.', 'ಟೈಪ್ ಮಾಡಿದಂತೆ ಕೆಳಗಿನ ಪಟ್ಟಿ ಚಿಕ್ಕದಾಗುತ್ತದೆ.'],
    ['The keyboard opens.', 'ಕೀಬೋರ್ಡ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  step(
    'inventory-new',
    ['+ New item', '+ ಹೊಸ ಸಾಮಾನು'],
    ['Adds an item the shop sells.', 'ಅಂಗಡಿ ಮಾರುವ ಸಾಮಾನು ಸೇರಿಸುತ್ತದೆ.'],
    ['You give its names, units (piece, pack, box) and prices.', 'ಹೆಸರು, ಘಟಕ (ತುಂಡು, ಪ್ಯಾಕ್, ಬಾಕ್ಸ್) ಮತ್ತು ಬೆಲೆ ಕೊಡುತ್ತೀರಿ.'],
    ['An empty item form opens. Nothing is saved until you tap Save.', 'ಖಾಲಿ ಫಾರ್ಮ್ ತೆರೆಯುತ್ತದೆ. ಉಳಿಸಿ ಒತ್ತುವವರೆಗೆ ಏನೂ ಉಳಿಯುವುದಿಲ್ಲ.'],
  ),
  step(
    'inventory-low',
    ['Only running low', 'ಮುಗಿಯುತ್ತಿರುವುದು ಮಾತ್ರ'],
    ['A tick to show only items below their level, all places together.', 'ಎಲ್ಲಾ ಕಡೆ ಸೇರಿ ಮಿತಿಗಿಂತ ಕಡಿಮೆ ಇರುವುದನ್ನು ಮಾತ್ರ ತೋರಿಸುವ ಟಿಕ್.'],
    ['The number beside it is how many are low.', 'ಪಕ್ಕದ ಸಂಖ್ಯೆ ಎಷ್ಟು ಕಡಿಮೆ ಇವೆ ಎಂದು.'],
    ['The list shows only those items.', 'ಪಟ್ಟಿಯಲ್ಲಿ ಅವು ಮಾತ್ರ ಕಾಣುತ್ತವೆ.'],
  ),
  step(
    'inventory-list',
    ['Every item, every place', 'ಪ್ರತಿ ಸಾಮಾನು, ಪ್ರತಿ ಸ್ಥಳ'],
    ['One row per item, a column per place, and the total.', 'ಪ್ರತಿ ಸಾಮಾನಿಗೆ ಒಂದು ಸಾಲು, ಪ್ರತಿ ಸ್ಥಳಕ್ಕೆ ಒಂದು ಕಾಲಂ, ಮತ್ತು ಒಟ್ಟು.'],
    ['Counts are said in the units you buy in, like “4 box 3 pc”. Red is below zero: count it.', 'ಎಣಿಕೆ ನೀವು ಕೊಳ್ಳುವ ಘಟಕದಲ್ಲಿ, ಉದಾ “4 ಬಾಕ್ಸ್ 3 ತುಂಡು”. ಕೆಂಪು ಎಂದರೆ ಸೊನ್ನೆಗಿಂತ ಕಡಿಮೆ: ಎಣಿಸಿ.'],
    ['That item’s page opens, where you correct its count.', 'ಆ ಸಾಮಾನಿನ ಪುಟ ತೆರೆಯುತ್ತದೆ, ಅಲ್ಲಿ ಎಣಿಕೆ ಸರಿಪಡಿಸಬಹುದು.'],
  ),
  step(
    'inventory-recount',
    ['Recount from the ledger', 'ಲೆಡ್ಜರ್‌ನಿಂದ ಮತ್ತೆ ಎಣಿಸಿ'],
    ['A check that every number agrees with the record of every change.', 'ಪ್ರತಿ ಸಂಖ್ಯೆ ಎಲ್ಲಾ ಬದಲಾವಣೆಗಳ ದಾಖಲೆಗೆ ಹೊಂದುತ್ತದೆಯೇ ಎಂಬ ಪರಿಶೀಲನೆ.'],
    ['The server does it every 5 minutes anyway; this does it now.', 'ಸರ್ವರ್ ಪ್ರತಿ 5 ನಿಮಿಷಕ್ಕೆ ಮಾಡುತ್ತದೆ; ಇದು ಈಗಲೇ ಮಾಡುತ್ತದೆ.'],
    ['A line says how many were checked and fixed. Real stock never changes.', 'ಎಷ್ಟು ಪರಿಶೀಲಿಸಿ ಸರಿಪಡಿಸಿತು ಎಂದು ಒಂದು ಸಾಲು. ನಿಜವಾದ ಸ್ಟಾಕ್ ಬದಲಾಗುವುದಿಲ್ಲ.'],
  ),
  step(
    'section-tabs',
    ['3D view', '3D ನೋಟ'],
    ['The shop and each godown in 3D, racks coloured green, amber, red or grey by their stock.', 'ಅಂಗಡಿ ಮತ್ತು ಪ್ರತಿ ಗೋದಾಮು 3D ಯಲ್ಲಿ, ಸ್ಟಾಕ್ ಪ್ರಕಾರ ರ‍್ಯಾಕ್ ಹಸಿರು, ಹಳದಿ, ಕೆಂಪು ಅಥವಾ ಬೂದು.'],
    ['Drag to turn, pinch to zoom; a rack lists its items and what to bring from the godown.', 'ತಿರುಗಿಸಲು ಎಳೆಯಿರಿ, ಜೂಮ್‌ಗೆ ಪಿಂಚ್; ರ‍್ಯಾಕ್ ಅದರ ಸಾಮಾನು ಮತ್ತು ಗೋದಾಮಿನಿಂದ ತರಬೇಕಾದ್ದು ತೋರಿಸುತ್ತದೆ.'],
    ['The 3D view tab opens.', '3D ನೋಟ ಟ್ಯಾಬ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  helpStep,
]);

export const itemTour = tour('item', ['An item', 'ಒಂದು ಸಾಮಾನು'], [
  step(
    'item-tabs',
    ['Stock · Details', 'ಸ್ಟಾಕ್ · ವಿವರ'],
    ['Two tabs for this item.', 'ಈ ಸಾಮಾನಿಗೆ ಎರಡು ಟ್ಯಾಬ್.'],
    ['Stock is where it is and how much; Details is its names, units and prices.', 'ಸ್ಟಾಕ್ ಎಲ್ಲಿ ಎಷ್ಟು ಇದೆ; ವಿವರ ಅದರ ಹೆಸರು, ಘಟಕ ಮತ್ತು ಬೆಲೆ.'],
    ['That tab opens.', 'ಆ ಟ್ಯಾಬ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  step(
    'item-summary',
    ['Stock at a glance', 'ಸ್ಟಾಕ್ ಒಂದೇ ನೋಟದಲ್ಲಿ'],
    ['The total in the default unit, each place, its value at cost, last bought and last sold.', 'ಮೊದಲ ಆಯ್ಕೆಯ ಘಟಕದಲ್ಲಿ ಒಟ್ಟು, ಪ್ರತಿ ಸ್ಥಳ, ಖರೀದಿ ಬೆಲೆಯಲ್ಲಿ ಮೌಲ್ಯ, ಕೊನೆಯ ಖರೀದಿ ಮತ್ತು ಮಾರಾಟ.'],
    ['Days left is the stock divided by the last 30 days of sales.', 'ಎಷ್ಟು ದಿನಕ್ಕೆ ಸಾಕು ಎಂಬುದು ಕಳೆದ 30 ದಿನದ ಮಾರಾಟದಿಂದ ಲೆಕ್ಕ.'],
    ['Nothing: it is worked out for you.', 'ಏನೂ ಇಲ್ಲ: ಇದು ತಾನಾಗಿ ಲೆಕ್ಕವಾಗುತ್ತದೆ.'],
  ),
  step(
    'item-places',
    ['Stock in each place', 'ಪ್ರತಿ ಸ್ಥಳದ ಸ್ಟಾಕ್'],
    ['The shop and each godown, with the rack it sits on. A number below that place’s running-out level is marked.', 'ಅಂಗಡಿ ಮತ್ತು ಪ್ರತಿ ಗೋದಾಮು, ಅದು ಇರುವ ರ‍್ಯಾಕ್ ಜೊತೆ. ಆ ಜಾಗದ ಮಟ್ಟಕ್ಕಿಂತ ಕಡಿಮೆ ಇದ್ದರೆ ಗುರುತಿಸಲಾಗುತ್ತದೆ.'],
    ['These numbers go down with bills and up with goods received.', 'ಬಿಲ್‌ನಿಂದ ಕಡಿಮೆ, ಸಾಮಾನು ಬಂದಾಗ ಹೆಚ್ಚು.'],
    ['Nothing: correct a number with the count box below.', 'ಏನೂ ಇಲ್ಲ: ಕೆಳಗಿನ ಎಣಿಕೆ ಡಬ್ಬಿಯಲ್ಲಿ ಸರಿಪಡಿಸಿ.'],
  ),
  step(
    'item-count',
    ['Correct the count', 'ಎಣಿಕೆ ಸರಿಪಡಿಸಿ'],
    ['Choose the place, and type what is really on the shelf.', 'ಸ್ಥಳ ಆರಿಸಿ, ಶೆಲ್ಫ್‌ನಲ್ಲಿ ನಿಜವಾಗಿ ಎಷ್ಟು ಇದೆ ಎಂದು ಟೈಪ್ ಮಾಡಿ.'],
    ['Count in boxes or packs: the screen shows what it comes to in pieces.', 'ಬಾಕ್ಸ್ ಅಥವಾ ಪ್ಯಾಕ್‌ನಲ್ಲಿ ಎಣಿಸಿ: ತುಂಡುಗಳಲ್ಲಿ ಎಷ್ಟು ಎಂದು ಪರದೆ ತೋರಿಸುತ್ತದೆ.'],
    ['Choosing the unit only changes how you count. Nothing is saved yet.', 'ಘಟಕ ಆರಿಸಿದರೆ ಎಣಿಸುವ ರೀತಿ ಮಾತ್ರ ಬದಲು. ಇನ್ನೂ ಉಳಿಸಿಲ್ಲ.'],
  ),
  step(
    'item-count-box',
    ['The number you counted', 'ನೀವು ಎಣಿಸಿದ ಸಂಖ್ಯೆ'],
    ['The whole count now, not the difference.', 'ಈಗಿನ ಒಟ್ಟು ಎಣಿಕೆ, ವ್ಯತ್ಯಾಸ ಅಲ್ಲ.'],
    ['Stock works out what changed for you.', 'ಏನು ಬದಲಾಯಿತು ಎಂದು ಸ್ಟಾಕ್ ತಾನೇ ಲೆಕ್ಕ ಹಾಕುತ್ತದೆ.'],
    ['The keyboard opens.', 'ಕೀಬೋರ್ಡ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  step(
    'item-save-count',
    ['Save count', 'ಎಣಿಕೆ ಉಳಿಸಿ'],
    ['Saves the count for that place.', 'ಆ ಸ್ಥಳದ ಎಣಿಕೆ ಉಳಿಸುತ್ತದೆ.'],
    ['The place’s stock becomes your number.', 'ಆ ಸ್ಥಳದ ಸ್ಟಾಕ್ ನಿಮ್ಮ ಸಂಖ್ಯೆ ಆಗುತ್ತದೆ.'],
    ['One line says what changed, and a “Counted” line appears in Last changes.', 'ಏನು ಬದಲಾಯಿತು ಎಂದು ಒಂದು ಸಾಲು, “ಎಣಿಸಿದ್ದು” ಸಾಲು ಕೊನೆಯ ಬದಲಾವಣೆಗಳಲ್ಲಿ ಬರುತ್ತದೆ.'],
  ),
  step(
    'item-default-unit',
    ['Units and the default unit (Details)', 'ಘಟಕಗಳು ಮತ್ತು ಮೊದಲ ಆಯ್ಕೆಯ ಘಟಕ (ವಿವರ)'],
    ['On Details: “+ Add unit” with any name, as “1 line = 12 pc”, and which unit comes first.', 'ವಿವರದಲ್ಲಿ: ಯಾವ ಹೆಸರಿನಲ್ಲೂ “+ ಘಟಕ ಸೇರಿಸಿ”, “1 ಲೈನ್ = 12 ಪೀಸ್” ಹಾಗೆ, ಮತ್ತು ಯಾವುದು ಮೊದಲು.'],
    ['Each unit can have “Price by quantity”: from this many, this rate; plus the lowest and highest rate.', 'ಪ್ರತಿ ಘಟಕಕ್ಕೆ “ಪ್ರಮಾಣದ ಪ್ರಕಾರ ಬೆಲೆ”: ಇಷ್ಟರಿಂದ ಈ ಬೆಲೆ; ಜೊತೆಗೆ ಕನಿಷ್ಠ ಮತ್ತು ಗರಿಷ್ಠ ಬೆಲೆ.'],
    ['Nothing changes until you tap Save.', 'ಉಳಿಸಿ ಒತ್ತುವವರೆಗೆ ಏನೂ ಬದಲಾಗುವುದಿಲ್ಲ.'],
  ),
  step(
    'item-suppliers',
    ['Suppliers of this item (Details)', 'ಈ ಸಾಮಾನಿನ ಸರಬರಾಜುದಾರರು (ವಿವರ)'],
    ['Who brings it: added by hand, and found in past purchase orders with the last cost.', 'ಯಾರು ತರುತ್ತಾರೆ: ಕೈಯಾರೆ ಸೇರಿಸಿದವರು, ಮತ್ತು ಹಿಂದಿನ ಖರೀದಿ ಆರ್ಡರ್‌ಗಳಿಂದ ಕೊನೆಯ ಬೆಲೆಯೊಂದಿಗೆ.'],
    ['A new purchase order suggests them for this item.', 'ಹೊಸ ಖರೀದಿ ಆರ್ಡರ್ ಈ ಸಾಮಾನಿಗೆ ಇವರನ್ನು ಸೂಚಿಸುತ್ತದೆ.'],
    ['Add supplier puts one on the list; Save keeps it.', 'ಸರಬರಾಜುದಾರ ಸೇರಿಸಿ ಪಟ್ಟಿಗೆ ಹಾಕುತ್ತದೆ; ಉಳಿಸಿ ಇಡುತ್ತದೆ.'],
  ),
  step(
    'item-moves',
    ['Last changes', 'ಕೊನೆಯ ಬದಲಾವಣೆಗಳು'],
    ['Every sale, transfer, purchase and count for this item.', 'ಈ ಸಾಮಾನಿನ ಪ್ರತಿ ಮಾರಾಟ, ಸಾಗಣೆ, ಖರೀದಿ ಮತ್ತು ಎಣಿಕೆ.'],
    ['It shows why the number is what it is.', 'ಸಂಖ್ಯೆ ಯಾಕೆ ಹೀಗಿದೆ ಎಂದು ತೋರಿಸುತ್ತದೆ.'],
    ['Nothing: it is a record. It is never edited.', 'ಏನೂ ಇಲ್ಲ: ಇದು ದಾಖಲೆ. ಎಂದೂ ಬದಲಿಸುವುದಿಲ್ಲ.'],
  ),
  helpStep,
]);

export const refillTour = tour('refill', ['Bring from godown', 'ಗೋದಾಮಿನಿಂದ ತರಿಸಿ'], [
  step(
    'section-tabs',
    ['Bring from godown', 'ಗೋದಾಮಿನಿಂದ ತರಿಸಿ'],
    ['The second tab of Inventory.', 'ಸಾಮಾನು ಭಾಗದ ಎರಡನೇ ಟ್ಯಾಬ್.'],
    ['It lists what is short on the shop shelf.', 'ಅಂಗಡಿ ಶೆಲ್ಫ್‌ನಲ್ಲಿ ಕಡಿಮೆ ಇರುವುದನ್ನು ಪಟ್ಟಿ ಮಾಡುತ್ತದೆ.'],
    ['Items & stock goes back to the full list.', 'ಸಾಮಾನು ಮತ್ತು ಸ್ಟಾಕ್ ಪೂರ್ಣ ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗುತ್ತದೆ.'],
  ),
  step(
    'refill-intro',
    ['How it is worked out', 'ಹೇಗೆ ಲೆಕ್ಕ'],
    ['Everything low in the shop, grouped by the godown that has most of it.', 'ಅಂಗಡಿಯಲ್ಲಿ ಕಡಿಮೆ ಇರುವುದೆಲ್ಲ, ಹೆಚ್ಚು ಇರುವ ಗೋದಾಮಿನಂತೆ ಗುಂಪು.'],
    ['So one trip brings it all, topping each item up to twice its level.', 'ಒಂದೇ ಓಡಾಟದಲ್ಲಿ ಎಲ್ಲ, ಪ್ರತಿ ಸಾಮಾನು ಮಿತಿಯ ಎರಡರಷ್ಟು ತುಂಬಿಸಿ.'],
    ['Nothing: it explains the list.', 'ಏನೂ ಇಲ್ಲ: ಪಟ್ಟಿಯನ್ನು ವಿವರಿಸುತ್ತದೆ.'],
  ),
  step(
    'refill-trip',
    ['One trip', 'ಒಂದು ಓಡಾಟ'],
    ['A card per godown: what the shop has, what the godown has, what to bring.', 'ಪ್ರತಿ ಗೋದಾಮಿಗೆ ಒಂದು ಕಾರ್ಡ್: ಅಂಗಡಿಯಲ್ಲಿ ಎಷ್ಟು, ಗೋದಾಮಿನಲ್ಲಿ ಎಷ್ಟು, ಎಷ್ಟು ತರಿಸಬೇಕು.'],
    ['Items already asked for or on the way are not shown twice.', 'ಈಗಾಗಲೇ ಕೇಳಿದ ಅಥವಾ ದಾರಿಯಲ್ಲಿರುವುದು ಮತ್ತೆ ಕಾಣುವುದಿಲ್ಲ.'],
    ['Nothing on the card itself; use its boxes and buttons.', 'ಕಾರ್ಡ್ ಒತ್ತಿದರೆ ಏನೂ ಇಲ್ಲ; ಅದರ ಡಬ್ಬಿ ಮತ್ತು ಗುಂಡಿ ಬಳಸಿ.'],
  ),
  step(
    'refill-qty',
    ['Bring', 'ತನ್ನಿ'],
    ['How much to bring, in boxes, packs or pieces.', 'ಎಷ್ಟು ತರಿಸಬೇಕು, ಬಾಕ್ಸ್, ಪ್ಯಾಕ್ ಅಥವಾ ತುಂಡುಗಳಲ್ಲಿ.'],
    ['Change it before sending; it never asks for more than the godown has.', 'ಕಳುಹಿಸುವ ಮೊದಲು ಬದಲಿಸಿ; ಗೋದಾಮಿನಲ್ಲಿ ಇರುವುದಕ್ಕಿಂತ ಹೆಚ್ಚು ಕೇಳುವುದಿಲ್ಲ.'],
    ['The keyboard opens. Nothing is sent yet.', 'ಕೀಬೋರ್ಡ್ ತೆರೆಯುತ್ತದೆ. ಇನ್ನೂ ಕಳುಹಿಸಿಲ್ಲ.'],
  ),
  step(
    'refill-remove',
    ['✕ Leave out', '✕ ಬಿಡಿ'],
    ['Takes one item off this trip.', 'ಈ ಓಡಾಟದಿಂದ ಒಂದು ಸಾಮಾನು ತೆಗೆಯುತ್ತದೆ.'],
    ['For something you do not want brought today.', 'ಇಂದು ತರಿಸಬೇಡ ಎನ್ನುವುದಕ್ಕೆ.'],
    ['The line greys out; “Add back” puts it back.', 'ಸಾಲು ಮಸುಕಾಗುತ್ತದೆ; “ಮತ್ತೆ ಸೇರಿಸಿ” ಹಿಂತಿರುಗಿಸುತ್ತದೆ.'],
  ),
  step(
    'refill-send',
    ['Send request', 'ಬೇಡಿಕೆ ಕಳುಹಿಸಿ'],
    ['Asks that godown to send these items to the shop.', 'ಈ ಸಾಮಾನುಗಳನ್ನು ಅಂಗಡಿಗೆ ಕಳುಹಿಸಲು ಆ ಗೋದಾಮಿಗೆ ಕೇಳುತ್ತದೆ.'],
    ['It becomes a transfer in Buy & move → Transfers.', 'ಇದು ಖರೀದಿ ಮತ್ತು ಸಾಗಣೆ → ಸಾಗಣೆಯಲ್ಲಿ ಒಂದು ಸಾಗಣೆ ಆಗುತ್ತದೆ.'],
    ['The godown sees it on their screen at once. Stock moves only when they send it.', 'ಗೋದಾಮಿನವರ ಪರದೆಯಲ್ಲಿ ತಕ್ಷಣ ಕಾಣುತ್ತದೆ. ಅವರು ಕಳುಹಿಸಿದಾಗ ಮಾತ್ರ ಸ್ಟಾಕ್ ಬದಲಾಗುತ್ತದೆ.'],
  ),
  step(
    'refill-buy',
    ['Low everywhere: buy', 'ಎಲ್ಲಾ ಕಡೆ ಕಡಿಮೆ: ಕೊಳ್ಳಿ'],
    ['Items low in the godowns too.', 'ಗೋದಾಮುಗಳಲ್ಲೂ ಕಡಿಮೆ ಇರುವ ಸಾಮಾನು.'],
    ['These need a supplier, not a trip.', 'ಇವಕ್ಕೆ ಓಡಾಟ ಅಲ್ಲ, ಸರಬರಾಜುದಾರ ಬೇಕು.'],
    ['“Order these” opens a new purchase with them filled in.', '“ಇವನ್ನು ಆರ್ಡರ್ ಮಾಡಿ” ಇವನ್ನು ತುಂಬಿದ ಹೊಸ ಖರೀದಿ ತೆರೆಯುತ್ತದೆ.'],
  ),
  helpStep,
]);

export const purchasesTour = tour('purchases', ['Purchases', 'ಖರೀದಿ'], [
  step(
    'section-tabs',
    ['Purchases · Transfers', 'ಖರೀದಿ · ಸಾಗಣೆ'],
    ['Buy & move has two tabs: goods from suppliers, and goods between your places.', 'ಖರೀದಿ ಮತ್ತು ಸಾಗಣೆಗೆ ಎರಡು ಟ್ಯಾಬ್: ಸರಬರಾಜುದಾರರಿಂದ ಸಾಮಾನು, ಮತ್ತು ನಿಮ್ಮ ಸ್ಥಳಗಳ ನಡುವೆ.'],
    ['Both bring stock up in a place when received.', 'ಎರಡೂ ಬಂದಾಗ ಆ ಸ್ಥಳದ ಸ್ಟಾಕ್ ಹೆಚ್ಚಿಸುತ್ತವೆ.'],
    ['That tab opens.', 'ಆ ಟ್ಯಾಬ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  step(
    'purchases-new',
    ['+ New order', '+ ಹೊಸ ಆರ್ಡರ್'],
    ['Writes down what you ordered from a supplier.', 'ಸರಬರಾಜುದಾರರಿಂದ ಏನು ಆರ್ಡರ್ ಮಾಡಿದಿರಿ ಎಂದು ಬರೆಯುತ್ತದೆ.'],
    ['Pick the supplier, where it goes, the items and their cost.', 'ಸರಬರಾಜುದಾರ, ಎಲ್ಲಿಗೆ, ಸಾಮಾನು ಮತ್ತು ಬೆಲೆ ಆರಿಸಿ.'],
    ['The order form opens. Saving it does not change stock yet.', 'ಆರ್ಡರ್ ಫಾರ್ಮ್ ತೆರೆಯುತ್ತದೆ. ಉಳಿಸಿದರೂ ಸ್ಟಾಕ್ ಇನ್ನೂ ಬದಲಾಗುವುದಿಲ್ಲ.'],
  ),
  step(
    'purchases-filter',
    ['Open · All · Suppliers', 'ತೆರೆದವು · ಎಲ್ಲ · ಸರಬರಾಜುದಾರರು'],
    ['Which orders to show, and your list of suppliers.', 'ಯಾವ ಆರ್ಡರ್ ತೋರಿಸಬೇಕು, ಮತ್ತು ಸರಬರಾಜುದಾರರ ಪಟ್ಟಿ.'],
    ['Open is what has not arrived yet.', 'ತೆರೆದವು ಎಂದರೆ ಇನ್ನೂ ಬಾರದವು.'],
    ['The list below changes. Suppliers lets you add a phone and notes.', 'ಕೆಳಗಿನ ಪಟ್ಟಿ ಬದಲಾಗುತ್ತದೆ. ಸರಬರಾಜುದಾರರಲ್ಲಿ ಫೋನ್ ಮತ್ತು ಟಿಪ್ಪಣಿ ಸೇರಿಸಬಹುದು.'],
  ),
  step(
    'purchases-groups',
    ['Order these, by supplier', 'ಇವನ್ನು ಆರ್ಡರ್ ಮಾಡಿ, ಸರಬರಾಜುದಾರರ ಪ್ರಕಾರ'],
    ['From the buy list, items are grouped by who usually supplies them.', 'ಖರೀದಿ ಪಟ್ಟಿಯಿಂದ, ಸಾಮಾನುಗಳು ಯಾವಾಗಲೂ ಕೊಡುವವರ ಪ್ರಕಾರ ಗುಂಪಾಗಿವೆ.'],
    ['One order is one supplier; under each item its suppliers and last cost show.', 'ಒಂದು ಆರ್ಡರ್ ಒಬ್ಬ ಸರಬರಾಜುದಾರ; ಪ್ರತಿ ಸಾಮಾನಿನ ಕೆಳಗೆ ಕೊಡುವವರು ಮತ್ತು ಕೊನೆಯ ಬೆಲೆ.'],
    ['Tapping a group fills the order with its items and that supplier.', 'ಗುಂಪು ಒತ್ತಿದರೆ ಅದರ ಸಾಮಾನು ಮತ್ತು ಸರಬರಾಜುದಾರ ಆರ್ಡರ್‌ಗೆ ಬರುತ್ತಾರೆ.'],
  ),
  step(
    'purchases-card',
    ['One order', 'ಒಂದು ಆರ್ಡರ್'],
    ['Supplier, where it goes, the items, quantities and cost.', 'ಸರಬರಾಜುದಾರ, ಎಲ್ಲಿಗೆ, ಸಾಮಾನು, ಪ್ರಮಾಣ ಮತ್ತು ಬೆಲೆ.'],
    ['It stays open until the goods arrive.', 'ಸಾಮಾನು ಬರುವವರೆಗೆ ತೆರೆದಿರುತ್ತದೆ.'],
    ['Nothing on the card; use its buttons.', 'ಕಾರ್ಡ್ ಒತ್ತಿದರೆ ಏನೂ ಇಲ್ಲ; ಗುಂಡಿಗಳನ್ನು ಬಳಸಿ.'],
  ),
  step(
    'purchases-receive',
    ['Mark received', 'ಬಂದಿದೆ ಎಂದು ಗುರುತಿಸಿ'],
    ['For when the goods are in front of you.', 'ಸಾಮಾನು ನಿಮ್ಮ ಮುಂದೆ ಬಂದಾಗ.'],
    ['You check what actually came and its cost, then “Save received”.', 'ನಿಜವಾಗಿ ಏನು ಬಂತು, ಬೆಲೆ ಎಷ್ಟು ಎಂದು ನೋಡಿ, ನಂತರ “ಬಂದಿದೆ ಎಂದು ಉಳಿಸಿ”.'],
    ['After saving, stock rises in that place and one line says by how much.', 'ಉಳಿಸಿದ ನಂತರ ಆ ಸ್ಥಳದ ಸ್ಟಾಕ್ ಹೆಚ್ಚುತ್ತದೆ, ಎಷ್ಟು ಎಂದು ಒಂದು ಸಾಲು ಹೇಳುತ್ತದೆ.'],
  ),
  step(
    'nav-move',
    ['Buy & move in the menu', 'ಮೆನುವಿನಲ್ಲಿ ಖರೀದಿ ಮತ್ತು ಸಾಗಣೆ'],
    ['Where purchases and transfers live.', 'ಖರೀದಿ ಮತ್ತು ಸಾಗಣೆ ಇರುವ ಜಾಗ.'],
    ['On a phone it is under “More”.', 'ಫೋನಿನಲ್ಲಿ “ಇನ್ನಷ್ಟು” ಒಳಗೆ.'],
    ['Purchases opens.', 'ಖರೀದಿ ತೆರೆಯುತ್ತದೆ.'],
  ),
  helpStep,
]);

export const transfersTour = tour('transfers', ['Transfers', 'ಸಾಗಣೆ'], [
  step(
    'section-tabs',
    ['Transfers', 'ಸಾಗಣೆ'],
    ['Goods moving between the shop and the godowns.', 'ಅಂಗಡಿ ಮತ್ತು ಗೋದಾಮುಗಳ ನಡುವೆ ಸಾಗುವ ಸಾಮಾನು.'],
    ['Each one goes: asked → sent → received.', 'ಪ್ರತಿಯೊಂದು: ಕೇಳಿದ್ದು → ಕಳುಹಿಸಿದ್ದು → ಬಂದದ್ದು.'],
    ['Purchases is the other tab, for goods from suppliers.', 'ಇನ್ನೊಂದು ಟ್ಯಾಬ್ ಖರೀದಿ, ಸರಬರಾಜುದಾರರ ಸಾಮಾನಿಗೆ.'],
  ),
  step(
    'transfers-new',
    ['+ New transfer', '+ ಹೊಸ ಸಾಗಣೆ'],
    ['Moves goods between any two places, by hand.', 'ಯಾವುದೇ ಎರಡು ಸ್ಥಳಗಳ ನಡುವೆ ಕೈಯಾರೆ ಸಾಮಾನು ಸಾಗಿಸುತ್ತದೆ.'],
    ['For the shop’s low items, Inventory → Bring from godown is quicker.', 'ಅಂಗಡಿಯಲ್ಲಿ ಕಡಿಮೆ ಇರುವುದಕ್ಕೆ, ಸಾಮಾನು → ಗೋದಾಮಿನಿಂದ ತರಿಸಿ ಬೇಗ.'],
    ['A form opens: from, to and the items. Saving asks the sending place.', 'ಫಾರ್ಮ್ ತೆರೆಯುತ್ತದೆ: ಇಂದ, ಗೆ, ಸಾಮಾನು. ಉಳಿಸಿದರೆ ಕಳುಹಿಸುವ ಸ್ಥಳಕ್ಕೆ ಕೇಳುತ್ತದೆ.'],
  ),
  step(
    'transfers-filter',
    ['Open · All', 'ತೆರೆದವು · ಎಲ್ಲ'],
    ['Open is asked or on the way; All includes finished ones.', 'ತೆರೆದವು ಎಂದರೆ ಕೇಳಿದ್ದು ಅಥವಾ ದಾರಿಯಲ್ಲಿ; ಎಲ್ಲ ಎಂದರೆ ಮುಗಿದವೂ.'],
    ['Filters the list below.', 'ಕೆಳಗಿನ ಪಟ್ಟಿಯನ್ನು ಸೋಸುತ್ತದೆ.'],
    ['The list changes. Nothing else.', 'ಪಟ್ಟಿ ಬದಲಾಗುತ್ತದೆ. ಬೇರೇನೂ ಇಲ್ಲ.'],
  ),
  step(
    'transfers-card',
    ['One transfer', 'ಒಂದು ಸಾಗಣೆ'],
    ['From, to, the vehicle and driver, and each item asked, sent and received.', 'ಇಂದ, ಗೆ, ವಾಹನ ಮತ್ತು ಚಾಲಕ, ಪ್ರತಿ ಸಾಮಾನು ಕೇಳಿದ್ದು, ಕಳುಹಿಸಿದ್ದು, ಬಂದದ್ದು.'],
    ['When the godown sends, its stock goes down; when it arrives, the shop’s goes up.', 'ಗೋದಾಮು ಕಳುಹಿಸಿದಾಗ ಅದರ ಸ್ಟಾಕ್ ಕಡಿಮೆ; ಬಂದಾಗ ಅಂಗಡಿಯದು ಹೆಚ್ಚು.'],
    ['Nothing on the card; use its buttons.', 'ಕಾರ್ಡ್ ಒತ್ತಿದರೆ ಏನೂ ಇಲ್ಲ; ಗುಂಡಿಗಳನ್ನು ಬಳಸಿ.'],
  ),
  step(
    'transfers-receive',
    ['Mark received', 'ಬಂದಿದೆ ಎಂದು ಗುರುತಿಸಿ'],
    ['For a transfer that has reached the shop.', 'ಅಂಗಡಿಗೆ ಬಂದ ಸಾಗಣೆಗೆ.'],
    ['Type what actually arrived first if it is short.', 'ಕಡಿಮೆ ಬಂದಿದ್ದರೆ ಮೊದಲು ನಿಜವಾಗಿ ಬಂದದ್ದನ್ನು ಟೈಪ್ ಮಾಡಿ.'],
    ['Stock rises in the shop and one line says by how much.', 'ಅಂಗಡಿಯ ಸ್ಟಾಕ್ ಹೆಚ್ಚುತ್ತದೆ, ಎಷ್ಟು ಎಂದು ಒಂದು ಸಾಲು ಹೇಳುತ್ತದೆ.'],
  ),
  step(
    'transfers-cancel',
    ['Cancel request', 'ಬೇಡಿಕೆ ರದ್ದು'],
    ['Only before the godown has sent it.', 'ಗೋದಾಮು ಕಳುಹಿಸುವ ಮೊದಲು ಮಾತ್ರ.'],
    ['Stops a request you no longer need.', 'ಬೇಡವಾದ ಬೇಡಿಕೆಯನ್ನು ನಿಲ್ಲಿಸುತ್ತದೆ.'],
    ['It is cancelled and leaves the godown’s screen. No stock moves.', 'ರದ್ದಾಗಿ ಗೋದಾಮಿನ ಪರದೆಯಿಂದ ಹೋಗುತ್ತದೆ. ಸ್ಟಾಕ್ ಬದಲಾಗುವುದಿಲ್ಲ.'],
  ),
  step(
    'deliveries-new',
    ['Deliveries', 'ಡೆಲಿವರಿ'],
    ['Home deliveries by a worker, with a pin on the map and 🏍 bike or 🚚 4-wheeler.', 'ಕೆಲಸಗಾರರ ಮನೆ ಡೆಲಿವರಿ, ನಕ್ಷೆಯಲ್ಲಿ ಪಿನ್ ಮತ್ತು 🏍 ಬೈಕ್ ಅಥವಾ 🚚 4 ಚಕ್ರ.'],
    ['The live map shows each worker on the way, gliding as their phone reports.', 'ದಾರಿಯಲ್ಲಿರುವ ಕೆಲಸಗಾರರನ್ನು ನಕ್ಷೆ ನೇರವಾಗಿ ತೋರಿಸುತ್ತದೆ.'],
    ['“+ New delivery” opens the form; a bill’s “🏠 Deliver” fills it.', '“+ ಹೊಸ ಡೆಲಿವರಿ” ಫಾರ್ಮ್ ತೆರೆಯುತ್ತದೆ; ಬಿಲ್‌ನ “🏠 ಡೆಲಿವರಿ” ತುಂಬಿಸುತ್ತದೆ.'],
  ),
  helpStep,
]);

export const setupTour = tour('setup', ['Setup', 'ಸೆಟಪ್'], [
  step(
    'section-tabs',
    ['Setup', 'ಸೆಟಪ್'],
    ['Places, People, Vehicles, Excel and Settings.', 'ಸ್ಥಳಗಳು, ಜನರು, ವಾಹನಗಳು, ಎಕ್ಸೆಲ್ ಮತ್ತು ಸೆಟ್ಟಿಂಗ್ಸ್.'],
    ['Things you set once and change rarely.', 'ಒಮ್ಮೆ ಹೊಂದಿಸಿ ಅಪರೂಪಕ್ಕೆ ಬದಲಿಸುವವು.'],
    ['That tab opens.', 'ಆ ಟ್ಯಾಬ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  step(
    'places-new',
    ['Places', 'ಸ್ಥಳಗಳು'],
    ['The shop and each godown.', 'ಅಂಗಡಿ ಮತ್ತು ಪ್ರತಿ ಗೋದಾಮು.'],
    ['Every count, transfer and purchase belongs to a place.', 'ಪ್ರತಿ ಎಣಿಕೆ, ಸಾಗಣೆ ಮತ್ತು ಖರೀದಿ ಒಂದು ಸ್ಥಳಕ್ಕೆ ಸೇರುತ್ತದೆ.'],
    ['“+ New place” opens a short form. Tapping a place edits it.', '“+ ಹೊಸ ಸ್ಥಳ” ಚಿಕ್ಕ ಫಾರ್ಮ್ ತೆರೆಯುತ್ತದೆ. ಸ್ಥಳ ಒತ್ತಿದರೆ ಬದಲಿಸಬಹುದು.'],
  ),
  step(
    'people-new',
    ['People', 'ಜನರು'],
    ['Who signs in: Admin or Worker. A worker also does the godown job.', 'ಯಾರು ಒಳಗೆ ಬರುತ್ತಾರೆ: ಆಡ್ಮಿನ್ ಅಥವಾ ಕೆಲಸಗಾರ. ಕೆಲಸಗಾರರು ಗೋದಾಮಿನ ಕೆಲಸವನ್ನೂ ಮಾಡುತ್ತಾರೆ.'],
    ['Each signs in with their phone and the PIN you give them.', 'ಪ್ರತಿಯೊಬ್ಬರೂ ಫೋನ್ ಮತ್ತು ನೀವು ಕೊಟ್ಟ ಪಿನ್‌ನಿಂದ ಒಳಗೆ ಬರುತ್ತಾರೆ.'],
    ['“+ New person” opens a form. Tapping a person changes their role, PIN, or switches them off.', '“+ ಹೊಸ ವ್ಯಕ್ತಿ” ಫಾರ್ಮ್ ತೆರೆಯುತ್ತದೆ. ವ್ಯಕ್ತಿ ಒತ್ತಿದರೆ ಪಾತ್ರ, ಪಿನ್ ಬದಲಿಸಬಹುದು, ಅಥವಾ ನಿಲ್ಲಿಸಬಹುದು.'],
  ),
  step(
    'vehicles-new',
    ['Vehicles', 'ವಾಹನಗಳು'],
    ['The shop’s tempo, auto or scooter, with its driver.', 'ಅಂಗಡಿಯ ಟೆಂಪೋ, ಆಟೋ ಅಥವಾ ಸ್ಕೂಟರ್, ಚಾಲಕನ ಜೊತೆ.'],
    ['Transfers and purchases offer them, so the godown picks one instead of typing.', 'ಸಾಗಣೆ ಮತ್ತು ಖರೀದಿಯಲ್ಲಿ ಇವು ಕಾಣುತ್ತವೆ, ಗೋದಾಮು ಟೈಪ್ ಮಾಡದೆ ಆರಿಸಬಹುದು.'],
    ['“+ New vehicle” opens a form.', '“+ ಹೊಸ ವಾಹನ” ಫಾರ್ಮ್ ತೆರೆಯುತ್ತದೆ.'],
  ),
  step(
    'files-download',
    ['Excel', 'ಎಕ್ಸೆಲ್'],
    ['Download items and stock, or bring items in from a file.', 'ಸಾಮಾನು ಮತ್ತು ಸ್ಟಾಕ್ ಡೌನ್‌ಲೋಡ್, ಅಥವಾ ಫೈಲ್‌ನಿಂದ ಸಾಮಾನು ತನ್ನಿ.'],
    ['A bring-in shows what it will add or change before anything is saved.', 'ತರುವ ಮೊದಲು ಏನು ಸೇರುತ್ತದೆ, ಬದಲಾಗುತ್ತದೆ ಎಂದು ತೋರಿಸುತ್ತದೆ.'],
    ['A download saves the file to this device.', 'ಡೌನ್‌ಲೋಡ್ ಫೈಲ್ ಈ ಸಾಧನದಲ್ಲಿ ಉಳಿಸುತ್ತದೆ.'],
  ),
  step(
    'settings-link',
    ['Settings: billing link', 'ಸೆಟ್ಟಿಂಗ್ಸ್: ಬಿಲ್ಲಿಂಗ್ ಸಂಪರ್ಕ'],
    ['Whether bills are coming in from billing, and the last bill read.', 'ಬಿಲ್ಲಿಂಗ್‌ನಿಂದ ಬಿಲ್ ಬರುತ್ತಿದೆಯೇ, ಕೊನೆಯ ಬಿಲ್ ಯಾವುದು.'],
    ['Bills are read every few seconds by themselves.', 'ಕೆಲವು ಸೆಕೆಂಡಿಗೊಮ್ಮೆ ಬಿಲ್‌ಗಳು ತಾನಾಗಿ ಓದಲ್ಪಡುತ್ತವೆ.'],
    ['“Read bills now” reads at once and says how many came.', '“ಈಗಲೇ ಬಿಲ್ ಓದಿ” ತಕ್ಷಣ ಓದಿ ಎಷ್ಟು ಬಂತು ಎಂದು ಹೇಳುತ್ತದೆ.'],
  ),
  step(
    'settings-round',
    ['Settings: rounding off', 'ಸೆಟ್ಟಿಂಗ್ಸ್: ರೌಂಡ್ ಆಫ್'],
    ['How bill totals are rounded: none, ₹1, ₹5 or ₹10.', 'ಬಿಲ್ ಮೊತ್ತ ಹೇಗೆ ರೌಂಡ್: ಬೇಡ, ₹1, ₹5 ಅಥವಾ ₹10.'],
    ['The worker screen, bills and reports show the rounded total.', 'ಕೆಲಸಗಾರರ ಪರದೆ, ಬಿಲ್ ಮತ್ತು ವರದಿಯಲ್ಲಿ ರೌಂಡ್ ಮೊತ್ತ.'],
    ['The choice is saved at once.', 'ಆಯ್ಕೆ ತಕ್ಷಣ ಉಳಿಯುತ್ತದೆ.'],
  ),
  helpStep,
]);
